---
    MODEL_NAME: MaskGit

    
    model_param:
    
      VQ_Configs:
        VQ_config_path: models/VQGAN/config/VQGAN.yml
        VQ_CKPT_path: models/VQGAN/checkpoints/VQGAN.pt
      
      num_image_tokens: 256
      num_codebook_vectors: 1024
      choice_temperature: 4.5
      gamma_type: cosine

      Transformer_param:
        num_image_tokens: 256
        num_codebook_vectors: 1024
        dim: 768
        n_layers: 15
        hidden_dim: 1536

